# Generated by Django 4.1.7 on 2023-03-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('autor', models.CharField(max_length=200)),
                ('read', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
